// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: admin_panel/v1/admin_panel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error_Code int32

const (
	Error_UNDEFINED_ERROR Error_Code = 0
)

// Enum value maps for Error_Code.
var (
	Error_Code_name = map[int32]string{
		0: "UNDEFINED_ERROR",
	}
	Error_Code_value = map[string]int32{
		"UNDEFINED_ERROR": 0,
	}
)

func (x Error_Code) Enum() *Error_Code {
	p := new(Error_Code)
	*p = x
	return p
}

func (x Error_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_panel_v1_admin_panel_proto_enumTypes[0].Descriptor()
}

func (Error_Code) Type() protoreflect.EnumType {
	return &file_admin_panel_v1_admin_panel_proto_enumTypes[0]
}

func (x Error_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Code.Descriptor instead.
func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return file_admin_panel_v1_admin_panel_proto_rawDescGZIP(), []int{2, 0}
}

type CreateDisciplineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CreateDisciplineRequest) Reset() {
	*x = CreateDisciplineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDisciplineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDisciplineRequest) ProtoMessage() {}

func (x *CreateDisciplineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDisciplineRequest.ProtoReflect.Descriptor instead.
func (*CreateDisciplineRequest) Descriptor() ([]byte, []int) {
	return file_admin_panel_v1_admin_panel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDisciplineRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateDisciplineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Discipline *Discipline `protobuf:"bytes,1,opt,name=discipline,proto3" json:"discipline,omitempty"`
	Errors     []*Error    `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *CreateDisciplineResponse) Reset() {
	*x = CreateDisciplineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDisciplineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDisciplineResponse) ProtoMessage() {}

func (x *CreateDisciplineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDisciplineResponse.ProtoReflect.Descriptor instead.
func (*CreateDisciplineResponse) Descriptor() ([]byte, []int) {
	return file_admin_panel_v1_admin_panel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDisciplineResponse) GetDiscipline() *Discipline {
	if x != nil {
		return x.Discipline
	}
	return nil
}

func (x *CreateDisciplineResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_admin_panel_v1_admin_panel_proto_rawDescGZIP(), []int{2}
}

type Discipline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Discipline) Reset() {
	*x = Discipline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discipline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discipline) ProtoMessage() {}

func (x *Discipline) ProtoReflect() protoreflect.Message {
	mi := &file_admin_panel_v1_admin_panel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discipline.ProtoReflect.Descriptor instead.
func (*Discipline) Descriptor() ([]byte, []int) {
	return file_admin_panel_v1_admin_panel_proto_rawDescGZIP(), []int{3}
}

func (x *Discipline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Discipline) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_admin_panel_v1_admin_panel_proto protoreflect.FileDescriptor

var file_admin_panel_v1_admin_panel_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x22,
	0x2f, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x7f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x69, 0x70,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a,
	0x64, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x2e, 0x44,
	0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x69,
	0x70, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61,
	0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x24, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1b, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x22, 0x32, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x69,
	0x70, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x32, 0x6d, 0x0a, 0x0a, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x12, 0x5f, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x24, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65,
	0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x69, 0x70, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x72, 0x74, 0x72, 0x69, 0x6b,
	0x61, 0x2f, 0x55, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_panel_v1_admin_panel_proto_rawDescOnce sync.Once
	file_admin_panel_v1_admin_panel_proto_rawDescData = file_admin_panel_v1_admin_panel_proto_rawDesc
)

func file_admin_panel_v1_admin_panel_proto_rawDescGZIP() []byte {
	file_admin_panel_v1_admin_panel_proto_rawDescOnce.Do(func() {
		file_admin_panel_v1_admin_panel_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_panel_v1_admin_panel_proto_rawDescData)
	})
	return file_admin_panel_v1_admin_panel_proto_rawDescData
}

var file_admin_panel_v1_admin_panel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_panel_v1_admin_panel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_panel_v1_admin_panel_proto_goTypes = []any{
	(Error_Code)(0),                  // 0: admin_panel.Error.Code
	(*CreateDisciplineRequest)(nil),  // 1: admin_panel.CreateDisciplineRequest
	(*CreateDisciplineResponse)(nil), // 2: admin_panel.CreateDisciplineResponse
	(*Error)(nil),                    // 3: admin_panel.Error
	(*Discipline)(nil),               // 4: admin_panel.Discipline
}
var file_admin_panel_v1_admin_panel_proto_depIdxs = []int32{
	4, // 0: admin_panel.CreateDisciplineResponse.discipline:type_name -> admin_panel.Discipline
	3, // 1: admin_panel.CreateDisciplineResponse.errors:type_name -> admin_panel.Error
	1, // 2: admin_panel.AdminPanel.CreateDiscipline:input_type -> admin_panel.CreateDisciplineRequest
	2, // 3: admin_panel.AdminPanel.CreateDiscipline:output_type -> admin_panel.CreateDisciplineResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_panel_v1_admin_panel_proto_init() }
func file_admin_panel_v1_admin_panel_proto_init() {
	if File_admin_panel_v1_admin_panel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_panel_v1_admin_panel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDisciplineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_panel_v1_admin_panel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDisciplineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_panel_v1_admin_panel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_panel_v1_admin_panel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Discipline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_panel_v1_admin_panel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_panel_v1_admin_panel_proto_goTypes,
		DependencyIndexes: file_admin_panel_v1_admin_panel_proto_depIdxs,
		EnumInfos:         file_admin_panel_v1_admin_panel_proto_enumTypes,
		MessageInfos:      file_admin_panel_v1_admin_panel_proto_msgTypes,
	}.Build()
	File_admin_panel_v1_admin_panel_proto = out.File
	file_admin_panel_v1_admin_panel_proto_rawDesc = nil
	file_admin_panel_v1_admin_panel_proto_goTypes = nil
	file_admin_panel_v1_admin_panel_proto_depIdxs = nil
}
