version: 3

tasks:
  help:
    desc: Отобразить список доступных команд с их описанием
    cmds:
      - task -l
    silent: true

  deps:
    desc: Установить зависимости
    cmds:
      - export GOOSE_DRIVER=postgres
      - export GOOSE_DBSTRING=postgresql://admin:321@localhost:9876/go_migrations?sslmode=disable

  gen:
    desc: Сгенерировать gRPC модели
    cmds:
      - mkdir -p ./pkg/proto/auth/v1
      - protoc -I proto ./proto/auth/v1/*.proto --go_out=./pkg/proto --go_opt=paths=source_relative --go-grpc_out=./pkg/proto --go-grpc_opt=paths=source_relative

  migrations_up:
    desc: Установить миграции
    cmds:
      - goose -dir ./migrations up

  migrations_down:
    desc: Откатить миграции
    cmds:
      - goose -dir ./migrations down
