version: 3

tasks:
  help:
    desc: Отобразить список доступных команд с их описанием
    cmds:
      - task -l
    silent: true

  deps:
    desc: Установить зависимости
    cmds:
      - export GOOSE_DRIVER=postgres
      - export GOOSE_DBSTRING=postgresql://admin:321@localhost:9876/inside_study?sslmode=disable

  gen:
    desc: Сгенерировать gRPC модели
    cmds:
      - mkdir -p ./pkg/proto/auth/v1
      - protoc -I proto ./proto/auth/v1/*.proto --go_out=./pkg/proto --go_opt=paths=source_relative --go-grpc_out=./pkg/proto --go-grpc_opt paths=source_relative
      - mkdir -p ./pkg/proto/admin_panel/v1
      - protoc -I proto ./proto/admin_panel/v1/*.proto --go_out=./pkg/proto --go_opt=paths=source_relative --go-grpc_out=./pkg/proto --go-grpc_opt=paths=source_relative
      - protoc -I proto ./proto/admin_panel/v1/*.proto --grpc-gateway_out=./pkg/proto --grpc-gateway_opt paths=source_relative --grpc-gateway_opt generate_unbound_methods=true
      - go generate ./...

  build:
    cmds:
      - go build -o ./build/main  ./cmd/sso/main.go

  up:
    cmds:
      - docker-compose up -d

  down:
    cmds:
      - docker-compose down

  test:
    desc: Запустить тесты (сервер запускается отдельно)
    cmds:
      - task migrations_up
      - task mock_data_up
      - go test ./tests -count=1 -v
      - task migrations_down

  migrations_up:
    desc: Установить миграции
    cmds:
      - goose -dir ./migrations up

  migrations_down:
    desc: Откатить миграции
    cmds:
      - goose -dir ./migrations down

  mock_data_up:
    desc: Добавить тестовые данные в БД
    cmds:
      - goose -dir ./tests/migrations up

  mock_data_down:
    desc: Удалить тестовые данные из БД
    cmds:
      - goose -dir ./tests/migrations down