// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID           int32
	NextAnswerID pgtype.Int4
	Title        string
}

type App struct {
	ID     int32
	Name   string
	Secret string
}

type Cause struct {
	ID        pgtype.UUID
	Title     string
	ProblemID pgtype.UUID
}

type Class struct {
	ID            pgtype.UUID
	Grade         int32
	Title         pgtype.Text
	MainTeacherID pgtype.UUID
	ReleaseDate   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type Problem struct {
	ID    pgtype.UUID
	Title string
}

type PsychologicalPerformance struct {
	ID                  int32
	OwnerID             int32
	PsychologicalTestID pgtype.Int4
	StartedAt           pgtype.Timestamptz
}

type PsychologicalTest struct {
	ID              int32
	FirstQuestionID pgtype.Int4
	TypeID          pgtype.Int4
	OwnerID         int32
	Title           string
}

type PsychologicalType struct {
	ID    int32
	Title string
}

type Question struct {
	ID             int32
	NextQuestionID pgtype.Int4
	Number         int32
	FirstAnswerID  pgtype.Int4
	Title          string
}

type Role struct {
	ID    int32
	Title string
}

type School struct {
	ID        pgtype.UUID
	LargeName string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Solution struct {
	ID        pgtype.UUID
	Title     string
	ProblemID pgtype.UUID
}

type User struct {
	ID         pgtype.UUID
	FirstName  string
	MiddleName string
	LastName   string
	Email      string
	PassHash   []byte
	Gender     pgtype.Bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
	RoleID     pgtype.Int4
	SchoolID   pgtype.UUID
	ClassesID  pgtype.UUID
}
