// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID           int32
	NextAnswerID pgtype.Int4
	Title        string
}

type App struct {
	ID     int32
	Name   string
	Secret string
}

type PsychologicalPerformance struct {
	ID                  int32
	OwnerID             int32
	PsychologicalTestID pgtype.Int4
	StartedAt           pgtype.Timestamptz
}

type PsychologicalTest struct {
	ID              int32
	FirstQuestionID pgtype.Int4
	TypeID          pgtype.Int4
	OwnerID         int32
	Title           string
}

type PsychologicalType struct {
	ID    int32
	Title string
}

type Question struct {
	ID             int32
	NextQuestionID pgtype.Int4
	Number         int32
	FirstAnswerID  pgtype.Int4
	Title          string
}

type User struct {
	ID       pgtype.UUID
	Email    string
	PassHash []byte
}
