// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	models "github.com/curtrika/UMetrika_server/internal/domain/models"
	schemas "github.com/curtrika/UMetrika_server/internal/storage/schemas"
)

type PsqlConverterImpl struct{}

func (c *PsqlConverterImpl) AppToModel(source schemas.AppSchema) models.App {
	var modelsApp models.App
	modelsApp.ID = source.ID
	modelsApp.Name = source.Name
	modelsApp.Secret = source.Secret
	return modelsApp
}
